# Generated by Django 6.0.2 on 2026-02-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('phone', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('comuna', models.CharField(choices=[('Santiago', 'Santiago'), ('Maipú', 'Maipú'), ('Pudahuel', 'Pudahuel'), ('Providencia', 'Providencia'), ('Las Condes', 'Las Condes')], max_length=60, verbose_name='Comuna')),
                ('property_type', models.CharField(choices=[('casa', 'Casa'), ('depto', 'Departamento'), ('local', 'Local/Oficina')], max_length=20, verbose_name='Tipo de inmueble')),
                ('service', models.CharField(choices=[('instalacion', 'Instalación'), ('venta', 'Venta de aire acondicionado'), ('reparacion', 'Reparación'), ('mantencion', 'Mantenimiento')], max_length=20, verbose_name='Servicio')),
                ('area_m2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Metros² aprox')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('contact_preference', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('both', 'Ambos')], default='both', max_length=10, verbose_name='Preferencia de contacto')),
                ('status', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('agendado', 'Agendado'), ('cerrado', 'Cerrado'), ('perdido', 'Perdido')], default='nuevo', max_length=12, verbose_name='Estado')),
            ],
        ),
    ]
