# Generated by Django 6.0.2 on 2026-02-11 02:02

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('comuna', models.CharField(blank=True, max_length=80, verbose_name='Comuna')),
                ('region', models.CharField(blank=True, default='RM', max_length=80, verbose_name='Región')),
                ('project_type', models.CharField(choices=[('casa', 'Casa'), ('depto', 'Departamento'), ('local', 'Local/Oficina')], default='casa', max_length=20, verbose_name='Tipo')),
                ('brand', models.CharField(blank=True, max_length=60, verbose_name='Marca')),
                ('btu', models.PositiveIntegerField(blank=True, null=True, verbose_name='BTU')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=projects.models.project_image_path)),
                ('alt', models.CharField(blank=True, max_length=140, verbose_name='Texto alternativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
