# Generated by Django 6.0.2 on 2026-09-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(blank=True, max_length=80, verbose_name='Región'),
        ),
    ]
