# Generated by Django 6.0.5 on 2026-10-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_region_sin_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['orden', '-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='orden',
            field=models.PositiveIntegerField(default=100, help_text='Más bajo sale primero. Deja 100 si no te importa el orden.', verbose_name='Orden'),
        ),
    ]
